### ISSUE TITLE
Wish: allow set-words after `set` and `copy` commands in PARSE rules

### ISSUE THREAD

**Issue by Oldes** [red/REP#88] opened 2020-11-30 16:24 UTC
Currently one can (must) write:
```
>> parse ["abc"] [set s string!] s
== "abc"
```
but it's not allowed to use `set-word!` for the `set` and `copy` parse commands. 
```
>> parse ["abc"] [set s: string!] s
*** Script Error: PARSE - unexpected end of rule after: set
*** Where: parse
```
That is common source of variable leaks when used in `function` definition, which is not able to find these words in parse rules... like:
```
>> s: 1 f: function[][parse ["abc"][set s string!]]  f 
== true
>> s
== "abc" ;<--- s was redefined!
```
One must manually define `s` as `local` in function definition:
```
>> s: 1 f: function[/local s][parse ["abc"][set s string!]]  f 
== true
>> s
== 1
```
Would it be a big problem to allow `set-word!` after `set` and `copy` (so it would be collected by `function` scanner)?
```
parse ["abc"][set s: string!]
```
PS: I know that set-words are used in parse for getting current position, but I think that should not be a problem.

**Comment by hiiamboris** [comment] 2020-11-30 16:56
dupe of https://github.com/red/REP/issues/60

**Comment by greggirwin** [comment] 2020-11-30 23:13
Closing as duplicate.

**Closed as completed by greggirwin** 2020-11-30 23:13 UTC
